import crypto from "node:crypto";
import {privateRequest,authStatus} from "./auth.js";

const mode=()=>String(process.env.TRADING_MODE||"paper").toLowerCase();
const armed=()=>process.env.LIVE_TRADING_ARMED==="YES_I_ACCEPT_LIVE_ORDER_RISK";
const maxLev=()=>Math.max(1,Number(process.env.MAX_LEVERAGE||3));
const maxNotional=()=>Math.max(1,Number(process.env.MAX_NOTIONAL_USD||100));
const liveAllowed=()=>mode()==="live"&&armed()&&authStatus().credentialsPresent;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

export function liveReadiness(){const a=authStatus();return {...a,armed:armed(),maxLeverage:maxLev(),maxNotionalUsd:maxNotional(),canSubmitLive:liveAllowed()};}
export function protectionPlan({side,entry,referencePrice,qty,stopPct=1.2,rewardR=2}){entry=Number(entry||referencePrice);qty=Number(qty);if(![entry,qty,stopPct,rewardR].every(Number.isFinite)||entry<=0||qty<=0)throw new Error("invalid protection inputs");const d=entry*stopPct/100,long=side==="Buy";return {stop:+(entry+(long?-d:d)).toFixed(8),takeProfit:+(entry+(long?d*rewardR:-d*rewardR)).toFixed(8),trigger:"MarkPrice",reduceOnly:true};}
export function validateIntent(i){const errors=[];if(!i?.symbol)errors.push("symbol");if(!["Buy","Sell"].includes(i?.side))errors.push("side");if(!(Number(i?.qty)>0))errors.push("qty");if(!(Number(i?.referencePrice)>0))errors.push("referencePrice");const lev=Number(i?.leverage||1),notional=Number(i?.qty)*Number(i?.referencePrice);if(lev>maxLev())errors.push("leverage_limit");if(notional>maxNotional())errors.push("notional_limit");if(Number(i?.marketAgeMs)>Number(process.env.MAX_MARKET_AGE_MS||10000))errors.push("stale_market");if(Number(i?.spreadBps||0)>Number(process.env.MAX_SPREAD_BPS||25))errors.push("spread");return {ok:errors.length===0,errors,notional:+notional.toFixed(2),leverage:lev};}
export async function submitLiveIntent(intent){const v=validateIntent(intent);if(!v.ok)throw new Error(`live intent rejected: ${v.errors.join(",")}`);if(!liveAllowed())throw new Error("live execution is not armed");const clOrdID=intent.clientOrderId||`pls-${crypto.randomUUID()}`,protection=protectionPlan(intent);const body={symbol:intent.symbol,side:intent.side,ordType:"Market",orderQty:Number(intent.qty),clOrdID,reduceOnly:false,takeProfitRp:String(protection.takeProfit),stopLossRp:String(protection.stop)};const result=await privateRequest("POST","/g-orders",{body});return {ok:true,clientOrderId:clOrdID,protection,result};}
export async function reconcileLive(symbol){if(!liveAllowed())return {ok:false,skipped:true,reason:"live_not_armed"};const query=`currency=USDT${symbol?`&symbol=${encodeURIComponent(symbol)}`:""}`;const [positions,orders]=await Promise.all([privateRequest("GET","/g-accounts/accountPositions",{query:"currency=USDT"}),privateRequest("GET","/g-orders/activeList",{query})]);return {ok:true,ts:new Date().toISOString(),positions:positions?.data||positions,orders:orders?.data||orders};}
export function protectionCoverage(orders=[],symbol){const xs=Array.isArray(orders)?orders:orders?.rows||orders?.data?.rows||[];const active=xs.filter(o=>(!symbol||o.symbol===symbol)&&o.reduceOnly!==false&&!['Canceled','Rejected','Filled'].includes(o.ordStatus));return {stop:active.some(o=>['Stop','StopMarket'].includes(o.ordType)),takeProfit:active.some(o=>['MarketIfTouched','TakeProfit','TakeProfitMarket'].includes(o.ordType)),activeCount:active.length};}
async function submitProtective(body,retries=2){let last;for(let n=0;n<=retries;n++){try{return await privateRequest("POST","/g-orders",{body});}catch(e){last=e;if(n<retries)await sleep(250*(2**n));}}throw last;}
export async function ensureProtection({symbol,side,qty,entry,referencePrice,stopPct=1.2,rewardR=2,existingOrders=[]}){if(!liveAllowed())throw new Error("live execution is not armed");const p=protectionPlan({side,qty,entry,referencePrice,stopPct,rewardR}),coverage=protectionCoverage(existingOrders,symbol),closeSide=side==="Buy"?"Sell":"Buy",common={symbol,side:closeSide,orderQty:Number(qty),reduceOnly:true,triggerType:"ByMarkPrice"},results=[];const needed=[];if(!coverage.stop)needed.push(["Stop",p.stop]);if(!coverage.takeProfit)needed.push(["MarketIfTouched",p.takeProfit]);for(const [kind,trigger] of needed){const body={...common,ordType:kind,stopPxRp:String(trigger),clOrdID:`protect-${kind.toLowerCase()}-${crypto.randomUUID()}`};results.push(await submitProtective(body));}return {ok:true,alreadyProtected:needed.length===0,created:needed.map(x=>x[0]),protection:p,results};}
