import express from "express";import {fetchProducts,fetchTicker24h,fetchOrderBook,fetchTrades,fetchKlines,BASE_URL,WS_URL} from "./phemex.js";import {rows,status} from "./state.js";import {startFeed} from "./ws.js";import {classify,riskState,setKill,paperEnter,paperMark,openPositions,idempotent} from "./trading.js";import {authStatus} from "./auth.js";import {liveReadiness,reconcileLive,verifyProtection} from "./execution.js";
const app=express();app.disable("x-powered-by");app.use(express.json({limit:"16kb"}));startFeed();
const opsToken=()=>String(process.env.OPS_TOKEN||"");function requireOps(q,r,n){const expected=opsToken();if(!expected)return r.status(503).json({error:"OPS_TOKEN is not configured"});const supplied=String(q.get("authorization")||"").replace(/^Bearer\s+/i,"");if(supplied!==expected)return r.status(401).json({error:"unauthorized"});n();}
app.get("/",(_q,r)=>r.json({service:"phemex-live-scanner",version:"2.2.0",mode:riskState().mode,rest:BASE_URL,ws:WS_URL,endpoints:["/health","/scan","/signals","/trading/status","/trading/readiness","/trading/positions","/market/:symbol","/products"]}));
app.get("/health",(_q,r)=>r.json({ok:true,ts:new Date().toISOString(),...status(),trading:riskState(),auth:authStatus(),live:liveReadiness()}));
app.get("/products",async(_q,r)=>{try{r.json(await fetchProducts())}catch(e){r.status(502).json({error:e.message})}});
app.get("/scan",(q,r)=>{const limit=Math.max(1,Math.min(50,Number(q.query.limit)||20));try{const all=rows();paperMark(all);const ranked=all.map(x=>({...x,classification:classify(x),signalSource:"Phemex WebSocket rolling samples"}));r.json({ts:new Date().toISOString(),source:"Phemex WebSocket rolling samples",...status(),ranked:ranked.slice(0,limit)})}catch(e){r.status(502).json({error:e.message})}});
app.get("/signals",(_q,r)=>{const all=rows();paperMark(all);r.json({ts:new Date().toISOString(),signals:all.map(x=>({...x,classification:classify(x)})).filter(x=>x.classification.eligible).slice(0,20)})});
app.get("/trading/status",(_q,r)=>r.json({trading:riskState(),auth:authStatus(),live:liveReadiness()}));app.get("/trading/readiness",(_q,r)=>r.json({ts:new Date().toISOString(),...liveReadiness()}));app.get("/trading/positions",(_q,r)=>r.json({positions:openPositions()}));
app.get("/trading/reconcile/:symbol?",requireOps,async(q,r)=>{try{const out=await reconcileLive(q.params.symbol?.toUpperCase());r.status(out.skipped?409:200).json(out)}catch(e){r.status(502).json({error:e.message})}});
app.get("/trading/protection/:symbol",requireOps,async(q,r)=>{try{const out=await verifyProtection({symbol:q.params.symbol.toUpperCase()});r.status(out.ok?200:409).json(out)}catch(e){r.status(502).json({error:e.message})}});
app.post("/trading/paper/enter",requireOps,(q,r)=>{const key=q.get("idempotency-key")||q.body?.idempotencyKey;if(!idempotent(key))return r.status(409).json({error:"duplicate or missing idempotency key"});const symbol=String(q.body?.symbol||"").toUpperCase();const x=rows().find(z=>z.symbol===symbol);if(!x)return r.status(404).json({error:"symbol not in live scanner"});const out=paperEnter(x);r.status(out.ok?201:422).json(out)});
app.post("/trading/kill",requireOps,(q,r)=>r.json(setKill(q.body?.enabled!==false)));
app.get("/market/:symbol",async(q,r)=>{try{const s=q.params.symbol.toUpperCase();const [ticker,book,trades,k1,k5]=await Promise.all([fetchTicker24h(s),fetchOrderBook(s),fetchTrades(s),fetchKlines(s,60,10),fetchKlines(s,300,10)]);r.json({ts:new Date().toISOString(),symbol:s,ticker,book,trades,kline1m:k1,kline5m:k5})}catch(e){r.status(502).json({error:e.message})}});
app.use((e,_q,r,_n)=>r.status(500).json({error:e.message}));const port=Number(process.env.PORT||3000);app.listen(port,"0.0.0.0",()=>console.log(`Phemex scanner v2.2 ready on 0.0.0.0:${port}`));
