import express from "express";import {fetchProducts,fetchTicker24h,fetchOrderBook,fetchTrades,fetchKlines,BASE_URL,WS_URL} from "./phemex.js";import {rows,status} from "./state.js";import {startFeed} from "./ws.js";
const app=express();app.use(express.json());startFeed();
const num=x=>{const n=Number(x);return Number.isFinite(n)?n:null};
function bars(j){const a=j?.result?.rows||j?.result||j?.data?.rows||j?.data||[];return Array.isArray(a)?a:[]}
function parseBar(b){if(Array.isArray(b)){const n=b.map(Number);return {ts:n[0],open:n[3]??n[1],high:n[4]??n[2],low:n[5]??n[3],close:n[6]??n[4],volume:n[7]??n[5]}}return {ts:num(b?.timestamp??b?.ts),open:num(b?.open),high:num(b?.high),low:num(b?.low),close:num(b?.close),volume:num(b?.volume)}}
const pct=(a,b)=>a!=null&&b!=null&&b!==0?((a-b)/b)*100:null;
async function enrich(x){try{const [k1,k5]=await Promise.all([fetchKlines(x.symbol,60,8),fetchKlines(x.symbol,300,4)]);const a1=bars(k1).map(parseBar).filter(z=>z.close!=null);const a5=bars(k5).map(parseBar).filter(z=>z.close!=null);const cur=x.last;const prev1=a1.at(-2)?.close??a1.at(-1)?.open??null;const prev5=a5.at(-2)?.close??a5.at(-1)?.open??null;const vols=a1.slice(-6).map(z=>z.volume).filter(Number.isFinite);const recent=vols.at(-1)??null,base=vols.length>1?vols.slice(0,-1).reduce((a,b)=>a+b,0)/(vols.length-1):null;return {...x,p1:pct(cur,prev1),p5:pct(cur,prev5),volumeAcceleration:recent!=null&&base>0?recent/base:null,ready1m:prev1!=null,ready5m:prev5!=null,signalSource:"Phemex REST klines"}}catch(e){return {...x,klineError:e.message,ready1m:false,ready5m:false,signalSource:"Phemex REST klines"}}}
app.get("/",(_q,r)=>r.json({service:"phemex-live-scanner",version:"1.1.0",mode:"public-read-only",rest:BASE_URL,ws:WS_URL,endpoints:["/health","/scan","/market/:symbol","/products"]}));
app.get("/health",(_q,r)=>r.json({ok:true,ts:new Date().toISOString(),...status()}));
app.get("/products",async(_q,r)=>{try{r.json(await fetchProducts())}catch(e){r.status(502).json({error:e.message})}});
app.get("/scan",async(q,r)=>{const limit=Math.max(1,Math.min(30,Number(q.query.limit)||20));const minTurnover=Number(q.query.minTurnover)||0;try{const base=rows().filter(x=>(x.turnover||0)>=minTurnover).slice(0,Math.max(limit,20));const ranked=await Promise.all(base.map(enrich));ranked.sort((a,b)=>((b.p1??-999)+(b.p5??-999))-((a.p1??-999)+(a.p5??-999)));r.json({ts:new Date().toISOString(),source:"Phemex live ticker + REST klines",...status(),ranked:ranked.slice(0,limit)})}catch(e){r.status(502).json({error:e.message})}});
app.get("/market/:symbol",async(q,r)=>{try{const s=q.params.symbol.toUpperCase();const [ticker,book,trades,k1,k5]=await Promise.all([fetchTicker24h(s),fetchOrderBook(s),fetchTrades(s),fetchKlines(s,60,10),fetchKlines(s,300,10)]);r.json({ts:new Date().toISOString(),symbol:s,ticker,book,trades,kline1m:k1,kline5m:k5})}catch(e){r.status(502).json({error:e.message})}});
app.use((e,_q,r,_n)=>r.status(500).json({error:e.message}));
const port=Number(process.env.PORT||3000);app.listen(port,"0.0.0.0",()=>console.log(`Phemex scanner v1.1 ready on 0.0.0.0:${port}`));