const history=new Map(); const books=new Map(); const trades=new Map(); let updatedAt=null;
const n=x=>{const v=Number(x);return Number.isFinite(v)?v:null};
export function ingestPack(msg){if(!Array.isArray(msg?.data)||!Array.isArray(msg?.fields))return;const f=msg.fields;for(const row of msg.data){const o=Object.fromEntries(f.map((k,i)=>[k,row[i]]));const s=o.symbol;if(!s)continue;const snap={symbol:s,open:n(o.openRp),high:n(o.highRp),low:n(o.lowRp),last:n(o.lastRp),volume:n(o.volumeRq),turnover:n(o.turnoverRv),openInterest:n(o.openInterestRv),index:n(o.indexRp),mark:n(o.markRp),funding:n(o.fundingRateRr),predFunding:n(o.predFundingRateRr),ts:Date.now()};const h=history.get(s)||[];h.push(snap);while(h.length>360)h.shift();history.set(s,h)}updatedAt=Date.now()}
export function ingestBook(msg){const s=msg?.symbol;if(!s||!msg.orderbook_p)return;books.set(s,{...msg.orderbook_p,ts:Date.now()})}
export function ingestTrades(msg){const s=msg?.symbol;if(!s||!Array.isArray(msg.trades_p))return;const old=trades.get(s)||[];old.push(...msg.trades_p.map(x=>({ts:Number(x[0]),side:x[1],price:n(x[2]),size:n(x[3])})));while(old.length>500)old.shift();trades.set(s,old)}
function pct(a,b){return a&&b?((a/b)-1)*100:null}
function ago(h,ms,key){const now=Date.now();for(let i=h.length-1;i>=0;i--)if(now-h[i].ts>=ms)return h[i][key];return h[0]?.[key]}
function imbalance(b){const sum=a=>(a||[]).slice(0,10).reduce((z,x)=>z+(Number(x[1])||0),0);const bid=sum(b?.bids),ask=sum(b?.asks);return bid+ask?(bid-ask)/(bid+ask):null}
function flow(t){const recent=t.filter(x=>Date.now()-x.ts/1e6<60000);let buy=0,sell=0;for(const x of recent)(x.side==="Buy"?buy+=x.size||0:sell+=x.size||0);return buy+sell?(buy-sell)/(buy+sell):null}
export function rows(){const out=[];for(const [symbol,h] of history){const x=h.at(-1);if(!x?.last)continue;const p1=pct(x.last,ago(h,60000,"last")),p5=pct(x.last,ago(h,300000,"last"));const v1=ago(h,60000,"volume"),v5=ago(h,300000,"volume");const va=v1!=null&&v5!=null?Math.max(0,(x.volume-v1)-((v1-v5)/4)):0;const oi1=ago(h,60000,"openInterest");const oiDelta=oi1&&x.openInterest?pct(x.openInterest,oi1):null;const obi=imbalance(books.get(symbol));const tf=flow(trades.get(symbol)||[]);const score=(p5||0)*4+(p1||0)*2+Math.log10(Math.max(1,va))*0.8+(oiDelta||0)*1.2+(obi||0)*2+(tf||0)*1.5;out.push({...x,p1:+(p1||0).toFixed(4),p5:+(p5||0).toFixed(4),volumeAcceleration:+va.toFixed(4),oiDelta1m:oiDelta==null?null:+oiDelta.toFixed(4),orderBookImbalance:obi==null?null:+obi.toFixed(4),tradeFlow1m:tf==null?null:+tf.toFixed(4),score:+score.toFixed(4)})}return out.sort((a,b)=>b.score-a.score)}
export const status=()=>({updatedAt,symbols:history.size,books:books.size,tradeStreams:trades.size});