const history=new Map(), books=new Map(), trades=new Map(); let updatedAt=null;
const n=x=>{const v=Number(x);return Number.isFinite(v)?v:null};
const now=()=>Date.now();

export function ingestPack(msg){if(!Array.isArray(msg?.data)||!Array.isArray(msg?.fields))return;const f=msg.fields,t=now();for(const row of msg.data){const o=Object.fromEntries(f.map((k,i)=>[k,row[i]])),s=o.symbol;if(!s)continue;const snap={symbol:s,open:n(o.openRp),high:n(o.highRp),low:n(o.lowRp),last:n(o.lastRp),volume:n(o.volumeRq),turnover:n(o.turnoverRv),openInterest:n(o.openInterestRv),index:n(o.indexRp),mark:n(o.markRp),funding:n(o.fundingRateRr),predFunding:n(o.predFundingRateRr),ts:t};const h=history.get(s)||[];h.push(snap);const cutoff=t-15*60e3;while(h.length>1&&h[0].ts<cutoff)h.shift();history.set(s,h)}updatedAt=t}
export function ingestBook(msg){const s=msg?.symbol;if(!s||!msg.orderbook_p)return;books.set(s,{...msg.orderbook_p,ts:now()})}
function tradeMs(v){const x=Number(v);if(!Number.isFinite(x))return now();if(x>1e17)return x/1e6;if(x>1e14)return x/1e3;if(x>1e11)return x;return x*1000}
export function ingestTrades(msg){const s=msg?.symbol;if(!s||!Array.isArray(msg.trades_p))return;const old=trades.get(s)||[];old.push(...msg.trades_p.map(x=>({ts:tradeMs(x[0]),side:x[1],price:n(x[2]),size:n(x[3])})));const cutoff=now()-5*60e3;while(old.length&&old[0].ts<cutoff)old.shift();while(old.length>2000)old.shift();trades.set(s,old)}
function pct(a,b){return Number.isFinite(a)&&Number.isFinite(b)&&b!==0?((a/b)-1)*100:null}
function atAge(h,ms,key){if(!h.length)return null;const target=(h.at(-1)?.ts??now())-ms;let best=null;for(const x of h){if(x.ts<=target)best=x;else break}return best?.[key]??null}
function imbalance(b){const sum=a=>(a||[]).slice(0,10).reduce((z,x)=>z+(Number(x[1])||0),0),bid=sum(b?.bids),ask=sum(b?.asks);return bid+ask?(bid-ask)/(bid+ask):null}
function flow(t){const cutoff=now()-60000;let buy=0,sell=0;for(const x of t)if(x.ts>=cutoff)(x.side==="Buy"?buy+=x.size||0:sell+=x.size||0);return buy+sell?(buy-sell)/(buy+sell):null}
export function rows(){const out=[];for(const [symbol,h] of history){const x=h.at(-1);if(!x?.last)continue;const l1=atAge(h,60000,"last"),l5=atAge(h,300000,"last"),p1=pct(x.last,l1),p5=pct(x.last,l5),v1=atAge(h,60000,"volume"),v5=atAge(h,300000,"volume");let va=null;if(v1!=null&&v5!=null&&x.volume!=null){const recent=Math.max(0,x.volume-v1),priorPerMin=Math.max(0,v1-v5)/4;va=priorPerMin>0?recent/priorPerMin:null}const oi1=atAge(h,60000,"openInterest"),oiDelta=pct(x.openInterest,oi1),obi=imbalance(books.get(symbol)),tf=flow(trades.get(symbol)||[]),ready1=l1!=null,ready5=l5!=null;const score=(p5??0)*4+(p1??0)*2+(va?Math.log10(Math.max(1,va))*1.5:0)+(oiDelta??0)*1.2+(obi??0)*2+(tf??0)*1.5;out.push({...x,p1:p1==null?null:+p1.toFixed(4),p5:p5==null?null:+p5.toFixed(4),volumeAcceleration:va==null?null:+va.toFixed(4),oiDelta1m:oiDelta==null?null:+oiDelta.toFixed(4),orderBookImbalance:obi==null?null:+obi.toFixed(4),tradeFlow1m:tf==null?null:+tf.toFixed(4),historySeconds:+((x.ts-h[0].ts)/1000).toFixed(1),samples:h.length,ready1m:ready1,ready5m:ready5,score:+score.toFixed(4)})}return out.sort((a,b)=>b.score-a.score)}
export const status=()=>({updatedAt,symbols:history.size,books:books.size,tradeStreams:trades.size,oldestHistorySeconds:Math.max(0,...[...history.values()].map(h=>h.length?(now()-h[0].ts)/1000:0))});